"""iqview/plugins/builtin/xor_mask.py

Built-in IQView Plugin: XOR Mask (De-whitening / Scrambling).

XORs `metadata["bits"]` with an input mask given in hex.
The mask pattern is repeated periodically and truncated to match the exact length of the data.
Includes built-in presets for common RF de-whitening standards (CC1101 PN9, CC2500, alternating, invert).
"""

from __future__ import annotations

import copy
import re
from typing import Any, Dict, List, Optional
import numpy as np

from iqview import PluginResult, PluginContext
from iqview.overlays import OverlayShape


PLUGIN_NAME              = "XOR Mask"
PLUGIN_DESCRIPTION       = (
    "XORs metadata['bits'] with a periodic hex mask or standard de-whitening sequence "
    "(CC1101 PN9, CC2500, Alternating, Invert), repeating and truncating to packet length."
)
PLUGIN_CATEGORY          = "Bit Manipulation"
PLUGIN_NEEDS_WIDEBAND_IQ = False

PLUGIN_DOC = """# XOR Mask (De-whitener)

Applies a bitwise XOR mask to `metadata["bits"]`. The mask is repeated periodically and truncated to the length of the data stream. Commonly used for data de-whitening, descrambling, and bit inversion.

### Presets
* **Custom Hex Mask**: Uses the user-defined `mask_hex` string (e.g. `0xAA`, `0x12345678`).
* **Invert All (0xFF)**: Flips every bit ($b_i \\oplus 1$).
* **Alternating (0xAA)**: Flips every second bit (`10101010`).
* **Alternating (0x55)**: `01010101`.
* **CC1101 PN9 / TI CC2500**: Standard 511-byte pseudo-random sequence generated by $x^9 + x^5 + 1$ with seed `0x1FF`.

### Parameters
* **Preset** (`preset`): Preset selection or `"Custom Hex Mask"`.
* **Mask (Hex)** (`mask_hex`): Custom hex mask string (e.g. `0xAA`, `0xD391`).
* **Byte Bit Order** (`bit_order`): `"msb_first"` (default) or `"lsb_first"` when unpacking mask bytes.

### Output Metadata
* `metadata["bits_pre_xor"]`: Bits before XOR mask
* `metadata["bits"]`: De-whitened / XORed bitstream
* `metadata["hex"]`: Hex formatted output
* `metadata["xor_mask_applied"]`: Hex representation of the mask applied
"""

PLUGIN_PARAMS = {
    "preset": {
        "type": "choice",
        "default": "Custom Hex Mask",
        "choices": [
            "Custom Hex Mask",
            "Invert All (0xFF)",
            "Alternating (0xAA)",
            "Alternating (0x55)",
            "CC1101 PN9",
            "TI CC2500",
        ],
        "preset_values": {
            "Invert All (0xFF)":  {"mask_hex": "0xFF"},
            "Alternating (0xAA)": {"mask_hex": "0xAA"},
            "Alternating (0x55)": {"mask_hex": "0x55"},
        },
        "label": "Preset",
        "tooltip": "Select a standard de-whitening preset or choose Custom Hex Mask.",
    },
    "mask_hex": {
        "type": "str",
        "default": "0xAA",
        "label": "Mask (Hex)",
        "tooltip": "Hex mask pattern to repeat across the data bits (e.g. 0xAA, 0xFF, 0x12345678).",
    },
    "bit_order": {
        "type": "choice",
        "default": "msb_first",
        "choices": ["msb_first", "lsb_first"],
        "label": "Byte Bit Order",
        "tooltip": "Order of bits unpacked from each mask byte (msb_first or lsb_first).",
    },
}


def _generate_pn9() -> bytes:
    """Generate the standard 511-byte PN9 de-whitening sequence (x^9 + x^5 + 1)."""
    lfsr = 0x1FF
    out_bytes = bytearray()
    for _ in range(511):
        b = 0
        for _ in range(8):
            # Output bit is bit 0
            bit = lfsr & 1
            # Feedback: bit 0 ^ bit 5
            fb = ((lfsr >> 0) ^ (lfsr >> 5)) & 1
            lfsr = (lfsr >> 1) | (fb << 8)
            b = (b << 1) | bit
        out_bytes.append(b)
    return bytes(out_bytes)


def _hex_to_mask_bits(hex_str: str, bit_order: str = "msb_first") -> np.ndarray:
    """Convert hex string to 1D uint8 bit mask array."""
    s = str(hex_str).strip()
    s = re.sub(r"^0[xX]", "", s)
    cleaned = re.sub(r"[^0-9a-fA-F]", "", s)
    if not cleaned:
        return np.array([0], dtype=np.uint8)
    if len(cleaned) % 2 != 0:
        cleaned = "0" + cleaned
    raw_bytes = bytes.fromhex(cleaned)
    bits = []
    for b in raw_bytes:
        if bit_order == "lsb_first":
            for s_idx in range(8):
                bits.append((b >> s_idx) & 1)
        else:
            for s_idx in range(7, -1, -1):
                bits.append((b >> s_idx) & 1)
    return np.asarray(bits, dtype=np.uint8)


def _apply_xor_mask(bits: np.ndarray, mask: np.ndarray) -> np.ndarray:
    """Tile mask across bits and compute XOR."""
    n_bits = len(bits)
    if n_bits == 0 or len(mask) == 0:
        return bits.copy()
    n_repeats = int(np.ceil(n_bits / float(len(mask))))
    mask_tiled = np.tile(mask, n_repeats)[:n_bits]
    return (bits ^ mask_tiled).astype(np.uint8)



def _parse_bits(raw: Any) -> Optional[np.ndarray]:
    """Parse 'bits' from overlay metadata into 1D uint8 bit array."""
    if raw is None:
        return None
    if isinstance(raw, str):
        cleaned = [1 if c in ("1", "T", "t") else 0 for c in raw if c in ("0", "1", "T", "t", "F", "f")]
        return np.asarray(cleaned, dtype=np.uint8) if cleaned else None
    if isinstance(raw, (list, tuple, np.ndarray)):
        arr = np.asarray(raw, dtype=np.uint8).ravel()
        return (arr != 0).astype(np.uint8) if len(arr) > 0 else None
    if isinstance(raw, (bytes, bytearray)):
        bits = []
        for b in raw:
            for s in range(7, -1, -1):
                bits.append((b >> s) & 1)
        return np.asarray(bits, dtype=np.uint8) if bits else None
    return None


def _bits_to_str(bits: np.ndarray) -> str:
    """Format bit array as binary string."""
    return "".join(str(int(b)) for b in bits)


def _bits_to_hex(bits: np.ndarray) -> str:
    """Convert bit array to formatted uppercase hex string."""
    n = len(bits)
    if n == 0:
        return ""
    pad_len = (8 - (n % 8)) % 8
    padded = np.pad(bits, (0, pad_len), constant_values=0) if pad_len > 0 else bits
    byte_vals = []
    for i in range(0, len(padded), 8):
        byte_val = 0
        for bit in padded[i : i + 8]:
            byte_val = (byte_val << 1) | int(bit)
        byte_vals.append(f"{byte_val:02X}")
    return " ".join(byte_vals)


def run(samples: np.ndarray, info: PluginContext) -> PluginResult:
    result = PluginResult()

    target_overlays = [
        o for o in info.overlays
        if o.shape == OverlayShape.RECT or (hasattr(o, "_shape_name") and o._shape_name() == "RECT")
    ]
    if not target_overlays:
        result.log("No Rect overlays found in active scope.")
        return result

    preset    = str(info.params.get("preset", "Custom Hex Mask"))
    mask_hex  = str(info.params.get("mask_hex", "0xAA")).strip()
    bit_order = str(info.params.get("bit_order", "msb_first"))

    # Resolve preset
    mask_label = mask_hex
    if "PN9" in preset or "CC2500" in preset or "CC1101" in preset:
        pn9_bytes = _generate_pn9()
        mask_bits = []
        for b in pn9_bytes:
            for s in range(7, -1, -1):
                mask_bits.append((b >> s) & 1)
        mask_arr = np.asarray(mask_bits, dtype=np.uint8)
        mask_label = "CC1101-PN9"
    elif "Invert" in preset or "0xFF" in preset:
        mask_arr = np.array([1, 1, 1, 1, 1, 1, 1, 1], dtype=np.uint8)
        mask_label = "0xFF (Invert)"
    elif "0x55" in preset:
        mask_arr = np.array([0, 1, 0, 1, 0, 1, 0, 1], dtype=np.uint8)
        mask_label = "0x55"
    elif "0xAA" in preset:
        mask_arr = np.array([1, 0, 1, 0, 1, 0, 1, 0], dtype=np.uint8)
        mask_label = "0xAA"
    else:
        mask_arr = _hex_to_mask_bits(mask_hex, bit_order=bit_order)
        mask_label = mask_hex

    if len(mask_arr) == 0:
        result.log(f"Invalid mask: {mask_hex!r}")
        return result

    masked_count = 0
    total = len(target_overlays)

    for idx, ov in enumerate(target_overlays):
        if info.is_cancelled():
            break

        info.progress(int((idx / total) * 100), f"Applying XOR mask {idx + 1}/{total}…")

        meta = ov.metadata or {}
        raw_bits = meta.get("bits")
        bits = _parse_bits(raw_bits)
        if bits is None or len(bits) == 0:
            continue

        out_bits = _apply_xor_mask(bits, mask_arr)

        new_meta = copy.deepcopy(meta)
        new_meta.update({
            "bits_pre_xor":       _bits_to_str(bits),
            "bits":               _bits_to_str(out_bits),
            "hex":                _bits_to_hex(out_bits),
            "num_bits":           len(out_bits),
            "xor_mask_applied":   mask_label,
        })

        base_label = (getattr(ov, "display_str", "") or "").split(" [XOR")[0].strip()
        if not base_label:
            base_label = f"Burst #{idx + 1}"
        new_label = f"{base_label} [XOR: {mask_label}]"

        base_hover = (getattr(ov, "hover_str", "") or "").strip()
        kept_lines = [ln for ln in base_hover.splitlines() if not ln.startswith("XOR:")]
        kept_lines.append(f"XOR: Masked {len(out_bits)} bits with {mask_label}")

        result.update(
            ov.id,
            display_str=new_label,
            hover_str="\n".join(kept_lines),
            metadata=new_meta,
        )
        masked_count += 1

    result.log(f"XOR Mask: Applied mask '{mask_label}' to {masked_count}/{total} burst(s).")
    info.progress(100, "Done")
    return result
